# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ratelimit_pb2 as ratelimit__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ratelimit_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RateServiceStub(object):
    """First gRPC service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetRate = channel.unary_unary(
                '/ratelimitapi.RateService/SetRate',
                request_serializer=ratelimit__pb2.ServiceRateMessage.SerializeToString,
                response_deserializer=ratelimit__pb2.Empty.FromString,
                _registered_method=True)
        self.GetRate = channel.unary_unary(
                '/ratelimitapi.RateService/GetRate',
                request_serializer=ratelimit__pb2.ServiceMessage.SerializeToString,
                response_deserializer=ratelimit__pb2.ServiceRateMessage.FromString,
                _registered_method=True)


class RateServiceServicer(object):
    """First gRPC service
    """

    def SetRate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetRate': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRate,
                    request_deserializer=ratelimit__pb2.ServiceRateMessage.FromString,
                    response_serializer=ratelimit__pb2.Empty.SerializeToString,
            ),
            'GetRate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRate,
                    request_deserializer=ratelimit__pb2.ServiceMessage.FromString,
                    response_serializer=ratelimit__pb2.ServiceRateMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ratelimitapi.RateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ratelimitapi.RateService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RateService(object):
    """First gRPC service
    """

    @staticmethod
    def SetRate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ratelimitapi.RateService/SetRate',
            ratelimit__pb2.ServiceRateMessage.SerializeToString,
            ratelimit__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ratelimitapi.RateService/GetRate',
            ratelimit__pb2.ServiceMessage.SerializeToString,
            ratelimit__pb2.ServiceRateMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RateLimitServiceStub(object):
    """Second gRPC service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IsRequestAllowed = channel.unary_unary(
                '/ratelimitapi.RateLimitService/IsRequestAllowed',
                request_serializer=ratelimit__pb2.RateLimitRequest.SerializeToString,
                response_deserializer=ratelimit__pb2.RateLimitResponse.FromString,
                _registered_method=True)


class RateLimitServiceServicer(object):
    """Second gRPC service
    """

    def IsRequestAllowed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RateLimitServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IsRequestAllowed': grpc.unary_unary_rpc_method_handler(
                    servicer.IsRequestAllowed,
                    request_deserializer=ratelimit__pb2.RateLimitRequest.FromString,
                    response_serializer=ratelimit__pb2.RateLimitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ratelimitapi.RateLimitService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ratelimitapi.RateLimitService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RateLimitService(object):
    """Second gRPC service
    """

    @staticmethod
    def IsRequestAllowed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ratelimitapi.RateLimitService/IsRequestAllowed',
            ratelimit__pb2.RateLimitRequest.SerializeToString,
            ratelimit__pb2.RateLimitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
