# redis-service.yaml (Redis Service)
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379 # Service port
      targetPort: 6379 # Redis container port
  type: 