# This rule is not used by the project ratelimiteroperator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over ratelimit.ratelimit.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ratelimiteroperator
    app.kubernetes.io/managed-by: kustomize
  name: ratelimitpolicy-admin-role
rules:
- apiGroups:
  - ratelimit.ratelimit.io
  resources:
  - ratelimitpolicies
  verbs:
  - '*'
- apiGroups:
  - ratelimit.ratelimit.io
  resources:
  - ratelimitpolicies/status
  verbs:
  - get
