---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ratelimit.ratelimit.io
  resources:
  - ratelimitpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ratelimit.ratelimit.io
  resources:
  - ratelimitpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - ratelimit.ratelimit.io
  resources:
  - ratelimitpolicies/status
  verbs:
  - get
  - patch
  - update
