# service.yaml (Microservice Service)
apiVersion: v1
kind: Service
metadata:
  name: dummy-service
spec:
  selector:
    app: dummy-service
  ports:
    - protocol: TCP
      port: 3002 # Service port
      targetPort: 3002 # Microservice container port
  type: NodePort