// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: proto/ratelimit.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request and response messages for ServiceOne
type ServiceMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceMessage) Reset() {
	*x = ServiceMessage{}
	mi := &file_proto_ratelimit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceMessage) ProtoMessage() {}

func (x *ServiceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratelimit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceMessage.ProtoReflect.Descriptor instead.
func (*ServiceMessage) Descriptor() ([]byte, []int) {
	return file_proto_ratelimit_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceMessage) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type ServiceRateMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Rpm           int32                  `protobuf:"varint,2,opt,name=rpm,proto3" json:"rpm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceRateMessage) Reset() {
	*x = ServiceRateMessage{}
	mi := &file_proto_ratelimit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRateMessage) ProtoMessage() {}

func (x *ServiceRateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratelimit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRateMessage.ProtoReflect.Descriptor instead.
func (*ServiceRateMessage) Descriptor() ([]byte, []int) {
	return file_proto_ratelimit_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceRateMessage) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ServiceRateMessage) GetRpm() int32 {
	if x != nil {
		return x.Rpm
	}
	return 0
}

type RateLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitRequest) Reset() {
	*x = RateLimitRequest{}
	mi := &file_proto_ratelimit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitRequest) ProtoMessage() {}

func (x *RateLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratelimit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitRequest.ProtoReflect.Descriptor instead.
func (*RateLimitRequest) Descriptor() ([]byte, []int) {
	return file_proto_ratelimit_proto_rawDescGZIP(), []int{2}
}

func (x *RateLimitRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RateLimitRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type RateLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAllowed     bool                   `protobuf:"varint,1,opt,name=isAllowed,proto3" json:"isAllowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitResponse) Reset() {
	*x = RateLimitResponse{}
	mi := &file_proto_ratelimit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitResponse) ProtoMessage() {}

func (x *RateLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratelimit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitResponse.ProtoReflect.Descriptor instead.
func (*RateLimitResponse) Descriptor() ([]byte, []int) {
	return file_proto_ratelimit_proto_rawDescGZIP(), []int{3}
}

func (x *RateLimitResponse) GetIsAllowed() bool {
	if x != nil {
		return x.IsAllowed
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_ratelimit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ratelimit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_ratelimit_proto_rawDescGZIP(), []int{4}
}

var File_proto_ratelimit_proto protoreflect.FileDescriptor

const file_proto_ratelimit_proto_rawDesc = "" +
	"\n" +
	"\x15proto/ratelimit.proto\x12\fratelimitapi\"*\n" +
	"\x0eServiceMessage\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"@\n" +
	"\x12ServiceRateMessage\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x10\n" +
	"\x03rpm\x18\x02 \x01(\x05R\x03rpm\"<\n" +
	"\x10RateLimitRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\"1\n" +
	"\x11RateLimitResponse\x12\x1c\n" +
	"\tisAllowed\x18\x01 \x01(\bR\tisAllowed\"\a\n" +
	"\x05Empty2\x9a\x01\n" +
	"\vRateService\x12@\n" +
	"\aSetRate\x12 .ratelimitapi.ServiceRateMessage\x1a\x13.ratelimitapi.Empty\x12I\n" +
	"\aGetRate\x12\x1c.ratelimitapi.ServiceMessage\x1a .ratelimitapi.ServiceRateMessage2g\n" +
	"\x10RateLimitService\x12S\n" +
	"\x10IsRequestAllowed\x12\x1e.ratelimitapi.RateLimitRequest\x1a\x1f.ratelimitapi.RateLimitResponseB\x0eZ\f./proto/grpcb\x06proto3"

var (
	file_proto_ratelimit_proto_rawDescOnce sync.Once
	file_proto_ratelimit_proto_rawDescData []byte
)

func file_proto_ratelimit_proto_rawDescGZIP() []byte {
	file_proto_ratelimit_proto_rawDescOnce.Do(func() {
		file_proto_ratelimit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ratelimit_proto_rawDesc), len(file_proto_ratelimit_proto_rawDesc)))
	})
	return file_proto_ratelimit_proto_rawDescData
}

var file_proto_ratelimit_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_ratelimit_proto_goTypes = []any{
	(*ServiceMessage)(nil),     // 0: ratelimitapi.ServiceMessage
	(*ServiceRateMessage)(nil), // 1: ratelimitapi.ServiceRateMessage
	(*RateLimitRequest)(nil),   // 2: ratelimitapi.RateLimitRequest
	(*RateLimitResponse)(nil),  // 3: ratelimitapi.RateLimitResponse
	(*Empty)(nil),              // 4: ratelimitapi.Empty
}
var file_proto_ratelimit_proto_depIdxs = []int32{
	1, // 0: ratelimitapi.RateService.SetRate:input_type -> ratelimitapi.ServiceRateMessage
	0, // 1: ratelimitapi.RateService.GetRate:input_type -> ratelimitapi.ServiceMessage
	2, // 2: ratelimitapi.RateLimitService.IsRequestAllowed:input_type -> ratelimitapi.RateLimitRequest
	4, // 3: ratelimitapi.RateService.SetRate:output_type -> ratelimitapi.Empty
	1, // 4: ratelimitapi.RateService.GetRate:output_type -> ratelimitapi.ServiceRateMessage
	3, // 5: ratelimitapi.RateLimitService.IsRequestAllowed:output_type -> ratelimitapi.RateLimitResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ratelimit_proto_init() }
func file_proto_ratelimit_proto_init() {
	if File_proto_ratelimit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ratelimit_proto_rawDesc), len(file_proto_ratelimit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_ratelimit_proto_goTypes,
		DependencyIndexes: file_proto_ratelimit_proto_depIdxs,
		MessageInfos:      file_proto_ratelimit_proto_msgTypes,
	}.Build()
	File_proto_ratelimit_proto = out.File
	file_proto_ratelimit_proto_goTypes = nil
	file_proto_ratelimit_proto_depIdxs = nil
}
